Add choice validate input #34
edemo/PDEngine pull request #172
Opened 2019-03-11 19:29 UTC by valentinbujdoso

@magwas 
Could you explain me this input validation?
String choiceId: id of existing choice in the vote with voteid

So the choiceId is valid when the Vote objects Choice list contains the choiceId?

2019-03-11 19:40 UTC, magwas commented
The underlying assumption is that a Choice does have an id, as the name can change.
See https://adadocs.demokracia.rulez.org/PDEngine/edemo/master/index.html#9a443205-d873-4413-8c2d-d6e1e7e5e520

2019-03-11 19:53 UTC, magwas requested changes
We also need to test all parameters.
For that I have to be sure what the parameters are. Maybe there is a model error here, please be patient while I figure out the Right Way(TM).

2019-03-11 19:53 UTC, magwas commented on src/main/java/org/rulez/demokracia/pdengine/ChoiceManager.java
> +		//if(vote.choices.containsKey(choiceName))
https://adadocs.demokracia.rulez.org/zenta-tools/magwas/master/zenta-tools/codingrules.html#961c75b2-2030-4f7d-83c2-4c4359028322

2019-03-11 19:53 UTC, magwas commented on src/main/java/org/rulez/demokracia/pdengine/ChoiceManager.java
> +		//return "Exception";
https://adadocs.demokracia.rulez.org/zenta-tools/magwas/master/zenta-tools/codingrules.html#961c75b2-2030-4f7d-83c2-4c4359028322

2019-03-11 19:53 UTC, magwas commented on src/test/java/org/rulez/demokracia/pdengine/ChoiceAddValidationTest.java
> +	//@tested_feature("Manage votes")
https://adadocs.demokracia.rulez.org/zenta-tools/magwas/master/zenta-tools/codingrules.html#961c75b2-2030-4f7d-83c2-4c4359028322

2019-03-11 19:55 UTC, magwas commented
Please disregard my above comment about choiceId. Cited wrong operation, and not sure whether the add choice operation is modelled right.

2019-03-11 20:01 UTC, magwas commented
The right operation:
POST /choice/<voteId>/<adminKey> (String choice) -> String choiceId
So no choiceId in parameters.
choice should still have to be input validated.
Updating the model shortly.

2019-03-11 20:17 UTC, valentinbujdoso commented
POST /choice/<voteId>/<adminKey> (String choice) -> String choiceId

so this way, right?

2019-03-11 20:35 UTC, magwas commented
> POST /choice/'voteId'/'adminKey' (String choice) -> String choiceId
> 
> so this way, right?

Yep, sorry for the silly markup.

> 
> @magwas The choice will be name of the Choice and the adminKey will be the username for the Choice, right?

The adminKey is a per-vote key, which can be used to administer the vote. This have been choosen to be made possible to create a vote without logging in. It is different from the username.
The username is planned to be injected by the controller code. This way there is no dependency to WS concepts in the code.

2019-03-11 20:54 UTC, valentinbujdoso commented
I have 1 question:
1st: I do not understand how can I create Choice without username. :(

2019-03-13 08:56 UTC, magwas approved these changes

2019-03-13 13:50 UTC, magwas commented
testcaseCount=3

2019-03-13 13:50 UTC, merged