Feature/cast vote validates input 59
edemo/PDEngine pull request #184
Opened 2019-03-14 09:38 UTC by colorimeter

Tests:
- String voteId: id of existing vote
- String ballotId: id of existing ballot
rankedChoices have a list of properly formatted RankedChoice instances, where:
- choiceId is the id of an existing choice
- rank is nonnegative integer

2019-03-14 10:09 UTC, magwas commented
Vitában állsz a sonarral.
A "Make choiceId a static final constant or non-public and provide accessors if needed" találat félig false positive: Legyen egy RankedChoiceEntity osztály, amiben _csak_ a mezők vannak benne, amik  publikusak, és abból származzon a RankedChoice, amiben a funkcionalitás van. Ha ez megtörtént, a sonarnak elmagyarázom, hogy ez false positive.

2019-03-14 10:15 UTC, colorimeter commented
Ok, kösz, épp ezt nézem. És a mutant teszthiba felejtős, vagy ezekre is rá
kell gyúrni?

On Thu, Mar 14, 2019 at 11:09 AM Árpád Magosányi <notifications@github.com>
wrote:

> Vitában állsz a sonarral.
> A "Make choiceId a static final constant or non-public and provide
> accessors if needed" találat félig false positive: Legyen egy
> RankedChoiceEntity osztály, amiben *csak* a mezők vannak benne, amik
> publikusak, és abból származzon a RankedChoice, amiben a funkcionalitás
> van. Ha ez megtörtént, a sonarnak elmagyarázom, hogy ez false positive.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/edemo/PDEngine/pull/184#issuecomment-472785521>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AuMPccPefK4oMHYEDo7I1qPmqHyKesYEks5vWh_sgaJpZM4bzsHJ>
> .
>

2019-03-14 10:34 UTC, magwas commented
A mutant hiba javitandó. Azért van, mert nem jó a tesztlefedettséged.

2019-03-14 11:43 UTC, magwas commented
a mutánst egy olyan testcase-el írthatod ki, amiben choice.rank=0

2019-03-14 13:14 UTC, colorimeter commented
OK, meglett. Az azóta küldött commitban már benne van ( good_rank = 0 néven kiemelve)

2019-03-14 20:54 UTC, magwas commented
A zombit még meg kéne ölni. Csinálj még egy tesztet, ahol a rank 0.

2019-03-15 13:13 UTC, magwas requested changes

2019-03-15 13:13 UTC, magwas commented on src/test/java/org/rulez/demokracia/pdengine/VoteTest.java
> +	@tested_behaviour("validates inputs")
The tested behaviour here is
@tested_behaviour("deletes the ballot with ballotId, so only one vote is possible with a ballot")

2019-03-15 13:13 UTC, magwas commented on src/test/java/org/rulez/demokracia/pdengine/VoteTest.java
>  	@tested_behaviour("deletes the ballot with ballotId, so only one vote is possible with a ballot")
This is @tested_behaviour("works only if canVote is true") in #168 
Which is already grabbed by valentinbujdoso.
We will figure out in email what to do with this.

2019-03-15 21:13 UTC, magwas approved these changes
nice

2019-03-15 21:13 UTC, merged