Feature/not logged in user cannot have ballot 196
edemo/PDEngine pull request #272
Opened 2019-03-17 21:56 UTC by colorimeter

TC:
- not logged in user cannot issue any ballot

2019-03-19 14:17 UTC, magwas requested changes

2019-03-19 14:17 UTC, magwas commented on src/main/java/org/rulez/demokracia/pdengine/VoteRegistry.java
> +import com.fasterxml.jackson.databind.Module.SetupContext;
Why?

2019-03-19 14:17 UTC, magwas commented on src/main/java/org/rulez/demokracia/pdengine/VoteRegistry.java
> +				throw new IllegalArgumentException("Anon admin already issued a ballot.");
There should be max 1 ballots per user, not altogether.

2019-03-19 14:17 UTC, magwas commented on src/main/java/org/rulez/demokracia/pdengine/VoteRegistry.java
> +				throw new IllegalArgumentException("Anon admin already issued a ballot.");
When the user already have a ballot, the right error message is something like "this user already have a ballot". But I am not sure that the check it right in the if.

2019-03-19 14:17 UTC, magwas commented on src/test/java/org/rulez/demokracia/pdengine/ObtainBallotAdminKeyTest.java
> +	public void even_if_the_user_does_have_all_the_assurances_he_cannot_issue_more_than_one_ballot() {
Perhaps add a test which makes sure that you can add a ballot for the user after you have added a ballot with admin key.
This would make your production code right.

2019-03-19 21:39 UTC, colorimeter commented on src/test/java/org/rulez/demokracia/pdengine/ObtainBallotAdminKeyTest.java
> +	public void even_if_the_user_does_have_all_the_assurances_he_cannot_issue_more_than_one_ballot() {
OK. Admin issues 2 ballots then the user 1.

2019-03-20 12:13 UTC, magwas approved these changes
nice work

2019-03-20 12:13 UTC, magwas commented
testcaseCount=3

2019-03-20 12:13 UTC, merged